# Generated by Django 5.2.3 on 2025-07-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField(default='No bio!')),
                ('is_programmer', models.BooleanField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('number_of_cars', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('height', models.FloatField()),
                ('profile_picture', models.FileField(upload_to='profiles/')),
            ],
            options={
                'db_table': 'PersonAsWeSaid',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.person')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ManyToManyField(to='poll.person')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.person')),
            ],
        ),
    ]
